### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by TheChampTF** [CrystalCraftMC/DarkHorse#3]

**Comment by jflory7** [comment]
Thanks, @TheChampTF. I can't guarantee a definite date on these feature requests, but I will certainly aim towards working on them.

**Comment by TheChampTF** [comment]
Thanks, much appreciated.

**Comment by justwheel** [comment]
@TheChampTF I'm not sure why you keep closing this, as the feedback is still valid. I don't see a reason to close this?

**Comment by justwheel** [comment]
@TheChampTF Any comments?
